import Vapor

struct BinancePair: Content {
  static let separator: String = ""
  let firstAsset: BinanceCoin
  let secondAsset: BinanceCoin
  
  var symbol: String {
    return "\(firstAsset.rawValue+BinancePair.separator)\(secondAsset.rawValue)"
  }
  
  init(firstAsset: BinanceCoin, secondAsset: BinanceCoin) {
    self.firstAsset = firstAsset
    self.secondAsset = secondAsset
  }
  
  init?(string: String) {
    let string = string.uppercased()
    for coin1 in BinanceCoin.allCases where string.hasPrefix(coin1.rawValue) {
      let suffix = string.replacingOccurrences(of: coin1.rawValue, with: "")
      for coin2 in BinanceCoin.allCases where suffix == coin2.rawValue {
        firstAsset = coin1
        secondAsset = coin2
        return
      }
    }
    return nil
  }
  
}

extension BinancePair: Hashable {
  var hashValue: Int {
    return (self.firstAsset.rawValue+self.secondAsset.rawValue).hashValue
  }
}


extension BinanceCoin: CaseIterable {}
enum BinanceCoin: String, Content {
  case ada = "ADA"
  case adx = "ADX"
  case ae = "AE"
  case agi = "AGI"
  case aion = "AION"
  case amb = "AMB"
  case appc = "APPC"
  case ardr = "ARDR"
  case ark = "ARK"
  case arn = "ARN"
  case ast = "AST"
  case bat = "BAT"
  case bcc = "BCC"
  case bcd = "BCD"
  case bchabc = "BCHABC"
  case bchsv = "BCHSV"
  case bcn = "BCN"
  case bcpt = "BCPT"
  case blz = "BLZ"
  case bnb = "BNB"
  case bnt = "BNT"
  case bqx = "BQX"
  case brd = "BRD"
  case btc = "BTC"
  case btg = "BTG"
  case bts = "BTS"
  case btt = "BTT"
  case cdt = "CDT"
  case celr = "CELR"
  case chat = "CHAT"
  case cloak = "CLOAK"
  case cmt = "CMT"
  case cnd = "CND"
  case cvc = "CVC"
  case dash = "DASH"
  case data = "DATA"
  case dcr = "DCR"
  case dent = "DENT"
  case dgd = "DGD"
  case dlt = "DLT"
  case dnt = "DNT"
  case dock = "DOCK"
  case edo = "EDO"
  case elf = "ELF"
  case eng = "ENG"
  case enj = "ENJ"
  case eos = "EOS"
  case etc = "ETC"
  case eth = "ETH"
  case evx = "EVX"
  case fet = "FET"
  case fuel = "FUEL"
  case fun = "FUN"
  case gas = "GAS"
  case gnt = "GNT"
  case go = "GO"
  case grs = "GRS"
  case gto = "GTO"
  case gvt = "GVT"
  case gxs = "GXS"
  case hc = "HC"
  case hot = "HOT"
  case hsr = "HSR"
  case icn = "ICN"
  case icx = "ICX"
  case ins = "INS"
  case iost = "IOST"
  case iota = "IOTA"
  case iotx = "IOTX"
  case key = "KEY"
  case kmd = "KMD"
  case knc = "KNC"
  case lend = "LEND"
  case link = "LINK"
  case loom = "LOOM"
  case lrc = "LRC"
  case lsk = "LSK"
  case ltc = "LTC"
  case lun = "LUN"
  case mana = "MANA"
  case mco = "MCO"
  case mda = "MDA"
  case mft = "MFT"
  case mith = "MITH"
  case mod = "MOD"
  case mth = "MTH"
  case mtl = "MTL"
  case nano = "NANO"
  case nas = "NAS"
  case nav = "NAV"
  case ncash = "NCASH"
  case nebl = "NEBL"
  case neo = "NEO"
  case npxs = "NPXS"
  case nuls = "NULS"
  case nxs = "NXS"
  case oax = "OAX"
  case omg = "OMG"
  case ong = "ONG"
  case ont = "ONT"
  case ost = "OST"
  case pax = "PAX"
  case phx = "PHX"
  case pivx = "PIVX"
  case poa = "POA"
  case poe = "POE"
  case poly = "POLY"
  case powr = "POWR"
  case ppt = "PPT"
  case qkc = "QKC"
  case qlc = "QLC"
  case qsp = "QSP"
  case qtum = "QTUM"
  case rcn = "RCN"
  case rdn = "RDN"
  case ren = "REN"
  case rep = "REP"
  case req = "REQ"
  case rlc = "RLC"
  case rpx = "RPX"
  case rvn = "RVN"
  case salt = "SALT"
  case sc = "SC"
  case sky = "SKY"
  case sngls = "SNGLS"
  case snm = "SNM"
  case snt = "SNT"
  case steem = "STEEM"
  case storj = "STORJ"
  case storm = "STORM"
  case strat = "STRAT"
  case sub = "SUB"
  case sys = "SYS"
  case theta = "THETA"
  case tnb = "TNB"
  case tnt = "TNT"
  case trig = "TRIG"
  case trx = "TRX"
  case tusd = "TUSD"
  case usdc = "USDC"
  case usds = "USDS"
  case usdt = "USDT"
  case usd = "USD"
  case ven = "VEN"
  case vet = "VET"
  case via = "VIA"
  case vib = "VIB"
  case vibe = "VIBE"
  case wabi = "WABI"
  case wan = "WAN"
  case waves = "WAVES"
  case wings = "WINGS"
  case wpr = "WPR"
  case wtc = "WTC"
  case xem = "XEM"
  case xlm = "XLM"
  case xmr = "XMR"
  case xrp = "XRP"
  case xvg = "XVG"
  case xzc = "XZC"
  case yoyo = "YOYO"
  case zec = "ZEC"
  case zen = "ZEN"
  case zil = "ZIL"
  case zrx = "ZRX"
  case atom = "ATOM"
  case bch = "BCH"
  case burst = "BURST"
  case clam = "CLAM"
  case dgb = "DGB"
  case doge = "DOGE"
  case fct = "FCT"
  case foam = "FOAM"
  case game = "GAME"
  case grin = "GRIN"
  case huc = "HUC"
  case lbc = "LBC"
  case lpt = "LPT"
  case maid = "MAID"
  case nmc = "NMC"
  case nmr = "NMR"
  case nxt = "NXT"
  case omni = "OMNI"
  case pasc = "PASC"
  case ppc = "PPC"
  case sbd = "SBD"
  case str = "STR"
  case vtc = "VTC"
  case xcp = "XCP"
  case xpm = "XPM"
}
